
name: first workflow
on: push
#   pull_request:
#     branches:    
#       - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: print hello
      run: |

          git config --global user.email "g.dubbaka@dxc.com" 
          git config --global user.name "ganesh110299"
           git clone https://github.com/ganesh110299/workflow.git
           
          ls
          cd workflow
          git checkout main
          echo $hi >> random.txt
          git add -A
          git commit -m "random file"
          git push --set-upstream origin main


