
name: blank
on: push
#   pull_request:
# branches:    
# - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: print hello
      run: |

          git config --global user.email "g.dubbaka@dxc.com" 
          git config --global user.name "ganesh110299"
          git clone git@github.com/ganesh110299/gh-first-action.git
          git remote add origin git@github.com/ganesh110299/gh-first-action.git        "
          ls
          cd workflow
          git checkout main
          echo hi >> random.txt
          git add -A
          git commit -m "random file"
          git push -f origin main 

